<?xml version="1.0" encoding="utf-8"?><Database Name="master" Class="L2SAccessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=3JS0082\justinsqlexpress;Initial Catalog=master;Integrated Security=True" SettingsObjectName="Password_Manager.Properties.Settings" SettingsPropertyName="masterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PMUsers" Member="PMUsers">
    <Type Name="PMUser">
      <Column Name="PMUsername" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PMPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateRegistered" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CanEditCompany" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Practice Table]" Member="Practice_Tables">
    <Type Name="Practice_Table">
      <Column Name="PracticeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PracticeNPI" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PracticeTaxID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PracticeName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PMUserSites" Member="PMUserSites">
    <Type Name="PMUserSite">
      <Column Name="userName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="siteName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="siteUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="siteId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sitePass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="practice" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PMCompanySites" Member="PMCompanySites">
    <Type Name="PMCompanySite">
      <Column Name="siteName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="practice" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="siteId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="sitePass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="siteUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="lastChanged" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lastChangedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>