#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Password_Manager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="master")]
	public partial class L2SAccessDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPMUser(PMUser instance);
    partial void UpdatePMUser(PMUser instance);
    partial void DeletePMUser(PMUser instance);
    #endregion
		
		public L2SAccessDataContext() : 
				base(global::Password_Manager.Properties.Settings.Default.masterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public L2SAccessDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public L2SAccessDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public L2SAccessDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public L2SAccessDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PMCompanySite> PMCompanySites
		{
			get
			{
				return this.GetTable<PMCompanySite>();
			}
		}
		
		public System.Data.Linq.Table<PMUser> PMUsers
		{
			get
			{
				return this.GetTable<PMUser>();
			}
		}
		
		public System.Data.Linq.Table<PMUserSite> PMUserSites
		{
			get
			{
				return this.GetTable<PMUserSite>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PMCompanySites")]
	public partial class PMCompanySite
	{
		
		private string _siteName;
		
		private string _siteUrl;
		
		private string _siteId;
		
		private string _sitePass;
		
		private System.DateTime _lastChanged;
		
		private System.Nullable<int> _practice;
		
		private string _notes;
		
		public PMCompanySite()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this._siteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteUrl", DbType="NVarChar(MAX)")]
		public string siteUrl
		{
			get
			{
				return this._siteUrl;
			}
			set
			{
				if ((this._siteUrl != value))
				{
					this._siteUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this._siteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitePass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sitePass
		{
			get
			{
				return this._sitePass;
			}
			set
			{
				if ((this._sitePass != value))
				{
					this._sitePass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastChanged", DbType="DateTime NOT NULL")]
		public System.DateTime lastChanged
		{
			get
			{
				return this._lastChanged;
			}
			set
			{
				if ((this._lastChanged != value))
				{
					this._lastChanged = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_practice", DbType="Int")]
		public System.Nullable<int> practice
		{
			get
			{
				return this._practice;
			}
			set
			{
				if ((this._practice != value))
				{
					this._practice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PMUsers")]
	public partial class PMUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PMUsername;
		
		private string _PMPassword;
		
		private System.DateTime _DateRegistered;
		
		private System.Nullable<bool> _CanEditCompany;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPMUsernameChanging(string value);
    partial void OnPMUsernameChanged();
    partial void OnPMPasswordChanging(string value);
    partial void OnPMPasswordChanged();
    partial void OnDateRegisteredChanging(System.DateTime value);
    partial void OnDateRegisteredChanged();
    partial void OnCanEditCompanyChanging(System.Nullable<bool> value);
    partial void OnCanEditCompanyChanged();
    #endregion
		
		public PMUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMUsername", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PMUsername
		{
			get
			{
				return this._PMUsername;
			}
			set
			{
				if ((this._PMUsername != value))
				{
					this.OnPMUsernameChanging(value);
					this.SendPropertyChanging();
					this._PMUsername = value;
					this.SendPropertyChanged("PMUsername");
					this.OnPMUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PMPassword
		{
			get
			{
				return this._PMPassword;
			}
			set
			{
				if ((this._PMPassword != value))
				{
					this.OnPMPasswordChanging(value);
					this.SendPropertyChanging();
					this._PMPassword = value;
					this.SendPropertyChanged("PMPassword");
					this.OnPMPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRegistered", DbType="DateTime NOT NULL")]
		public System.DateTime DateRegistered
		{
			get
			{
				return this._DateRegistered;
			}
			set
			{
				if ((this._DateRegistered != value))
				{
					this.OnDateRegisteredChanging(value);
					this.SendPropertyChanging();
					this._DateRegistered = value;
					this.SendPropertyChanged("DateRegistered");
					this.OnDateRegisteredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanEditCompany", DbType="Bit")]
		public System.Nullable<bool> CanEditCompany
		{
			get
			{
				return this._CanEditCompany;
			}
			set
			{
				if ((this._CanEditCompany != value))
				{
					this.OnCanEditCompanyChanging(value);
					this.SendPropertyChanging();
					this._CanEditCompany = value;
					this.SendPropertyChanged("CanEditCompany");
					this.OnCanEditCompanyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PMUserSites")]
	public partial class PMUserSite
	{
		
		private string _siteName;
		
		private string _siteUrl;
		
		private string _siteId;
		
		private string _sitePass;
		
		private System.Nullable<int> _practice;
		
		private string _notes;
		
		public PMUserSite()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this._siteName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteUrl", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string siteUrl
		{
			get
			{
				return this._siteUrl;
			}
			set
			{
				if ((this._siteUrl != value))
				{
					this._siteUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this._siteId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitePass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sitePass
		{
			get
			{
				return this._sitePass;
			}
			set
			{
				if ((this._sitePass != value))
				{
					this._sitePass = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_practice", DbType="Int")]
		public System.Nullable<int> practice
		{
			get
			{
				return this._practice;
			}
			set
			{
				if ((this._practice != value))
				{
					this._practice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this._notes = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
