#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Password_Manager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="master")]
	public partial class L2SAccessDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPMUser(PMUser instance);
    partial void UpdatePMUser(PMUser instance);
    partial void DeletePMUser(PMUser instance);
    partial void InsertPractice_Table(Practice_Table instance);
    partial void UpdatePractice_Table(Practice_Table instance);
    partial void DeletePractice_Table(Practice_Table instance);
    partial void InsertPMUserSite(PMUserSite instance);
    partial void UpdatePMUserSite(PMUserSite instance);
    partial void DeletePMUserSite(PMUserSite instance);
    partial void InsertPMCompanySite(PMCompanySite instance);
    partial void UpdatePMCompanySite(PMCompanySite instance);
    partial void DeletePMCompanySite(PMCompanySite instance);
    #endregion
		
		public L2SAccessDataContext() : 
				base(global::Password_Manager.Properties.Settings.Default.masterConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public L2SAccessDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public L2SAccessDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public L2SAccessDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public L2SAccessDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PMUser> PMUsers
		{
			get
			{
				return this.GetTable<PMUser>();
			}
		}
		
		public System.Data.Linq.Table<Practice_Table> Practice_Tables
		{
			get
			{
				return this.GetTable<Practice_Table>();
			}
		}
		
		public System.Data.Linq.Table<PMUserSite> PMUserSites
		{
			get
			{
				return this.GetTable<PMUserSite>();
			}
		}
		
		public System.Data.Linq.Table<PMCompanySite> PMCompanySites
		{
			get
			{
				return this.GetTable<PMCompanySite>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PMUsers")]
	public partial class PMUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PMUsername;
		
		private string _PMPassword;
		
		private System.DateTime _DateRegistered;
		
		private System.Nullable<bool> _CanEditCompany;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPMUsernameChanging(string value);
    partial void OnPMUsernameChanged();
    partial void OnPMPasswordChanging(string value);
    partial void OnPMPasswordChanged();
    partial void OnDateRegisteredChanging(System.DateTime value);
    partial void OnDateRegisteredChanged();
    partial void OnCanEditCompanyChanging(System.Nullable<bool> value);
    partial void OnCanEditCompanyChanged();
    #endregion
		
		public PMUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMUsername", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PMUsername
		{
			get
			{
				return this._PMUsername;
			}
			set
			{
				if ((this._PMUsername != value))
				{
					this.OnPMUsernameChanging(value);
					this.SendPropertyChanging();
					this._PMUsername = value;
					this.SendPropertyChanged("PMUsername");
					this.OnPMUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PMPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PMPassword
		{
			get
			{
				return this._PMPassword;
			}
			set
			{
				if ((this._PMPassword != value))
				{
					this.OnPMPasswordChanging(value);
					this.SendPropertyChanging();
					this._PMPassword = value;
					this.SendPropertyChanged("PMPassword");
					this.OnPMPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateRegistered", DbType="DateTime NOT NULL")]
		public System.DateTime DateRegistered
		{
			get
			{
				return this._DateRegistered;
			}
			set
			{
				if ((this._DateRegistered != value))
				{
					this.OnDateRegisteredChanging(value);
					this.SendPropertyChanging();
					this._DateRegistered = value;
					this.SendPropertyChanged("DateRegistered");
					this.OnDateRegisteredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanEditCompany", DbType="Bit")]
		public System.Nullable<bool> CanEditCompany
		{
			get
			{
				return this._CanEditCompany;
			}
			set
			{
				if ((this._CanEditCompany != value))
				{
					this.OnCanEditCompanyChanging(value);
					this.SendPropertyChanging();
					this._CanEditCompany = value;
					this.SendPropertyChanged("CanEditCompany");
					this.OnCanEditCompanyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Practice Table]")]
	public partial class Practice_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PracticeID;
		
		private int _PracticeNPI;
		
		private int _PracticeTaxID;
		
		private string _PracticeName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPracticeIDChanging(int value);
    partial void OnPracticeIDChanged();
    partial void OnPracticeNPIChanging(int value);
    partial void OnPracticeNPIChanged();
    partial void OnPracticeTaxIDChanging(int value);
    partial void OnPracticeTaxIDChanged();
    partial void OnPracticeNameChanging(string value);
    partial void OnPracticeNameChanged();
    #endregion
		
		public Practice_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PracticeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PracticeID
		{
			get
			{
				return this._PracticeID;
			}
			set
			{
				if ((this._PracticeID != value))
				{
					this.OnPracticeIDChanging(value);
					this.SendPropertyChanging();
					this._PracticeID = value;
					this.SendPropertyChanged("PracticeID");
					this.OnPracticeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PracticeNPI", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PracticeNPI
		{
			get
			{
				return this._PracticeNPI;
			}
			set
			{
				if ((this._PracticeNPI != value))
				{
					this.OnPracticeNPIChanging(value);
					this.SendPropertyChanging();
					this._PracticeNPI = value;
					this.SendPropertyChanged("PracticeNPI");
					this.OnPracticeNPIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PracticeTaxID", DbType="Int NOT NULL")]
		public int PracticeTaxID
		{
			get
			{
				return this._PracticeTaxID;
			}
			set
			{
				if ((this._PracticeTaxID != value))
				{
					this.OnPracticeTaxIDChanging(value);
					this.SendPropertyChanging();
					this._PracticeTaxID = value;
					this.SendPropertyChanged("PracticeTaxID");
					this.OnPracticeTaxIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PracticeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PracticeName
		{
			get
			{
				return this._PracticeName;
			}
			set
			{
				if ((this._PracticeName != value))
				{
					this.OnPracticeNameChanging(value);
					this.SendPropertyChanging();
					this._PracticeName = value;
					this.SendPropertyChanged("PracticeName");
					this.OnPracticeNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PMUserSites")]
	public partial class PMUserSite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _userName;
		
		private string _siteName;
		
		private string _siteUrl;
		
		private string _siteId;
		
		private string _sitePass;
		
		private int _practice;
		
		private string _notes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnsiteNameChanging(string value);
    partial void OnsiteNameChanged();
    partial void OnsiteUrlChanging(string value);
    partial void OnsiteUrlChanged();
    partial void OnsiteIdChanging(string value);
    partial void OnsiteIdChanged();
    partial void OnsitePassChanging(string value);
    partial void OnsitePassChanged();
    partial void OnpracticeChanging(int value);
    partial void OnpracticeChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    #endregion
		
		public PMUserSite()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string userName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if ((this._userName != value))
				{
					this.OnuserNameChanging(value);
					this.SendPropertyChanging();
					this._userName = value;
					this.SendPropertyChanged("userName");
					this.OnuserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this.OnsiteNameChanging(value);
					this.SendPropertyChanging();
					this._siteName = value;
					this.SendPropertyChanged("siteName");
					this.OnsiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteUrl", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string siteUrl
		{
			get
			{
				return this._siteUrl;
			}
			set
			{
				if ((this._siteUrl != value))
				{
					this.OnsiteUrlChanging(value);
					this.SendPropertyChanging();
					this._siteUrl = value;
					this.SendPropertyChanged("siteUrl");
					this.OnsiteUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="NVarChar(50)")]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitePass", DbType="NVarChar(50)")]
		public string sitePass
		{
			get
			{
				return this._sitePass;
			}
			set
			{
				if ((this._sitePass != value))
				{
					this.OnsitePassChanging(value);
					this.SendPropertyChanging();
					this._sitePass = value;
					this.SendPropertyChanged("sitePass");
					this.OnsitePassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_practice", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int practice
		{
			get
			{
				return this._practice;
			}
			set
			{
				if ((this._practice != value))
				{
					this.OnpracticeChanging(value);
					this.SendPropertyChanging();
					this._practice = value;
					this.SendPropertyChanged("practice");
					this.OnpracticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PMCompanySites")]
	public partial class PMCompanySite : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _siteName;
		
		private int _practice;
		
		private string _siteId;
		
		private string _sitePass;
		
		private string _siteUrl;
		
		private string _lastChanged;
		
		private string _notes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsiteNameChanging(string value);
    partial void OnsiteNameChanged();
    partial void OnpracticeChanging(int value);
    partial void OnpracticeChanged();
    partial void OnsiteIdChanging(string value);
    partial void OnsiteIdChanged();
    partial void OnsitePassChanging(string value);
    partial void OnsitePassChanged();
    partial void OnsiteUrlChanging(string value);
    partial void OnsiteUrlChanged();
    partial void OnlastChangedChanging(string value);
    partial void OnlastChangedChanged();
    partial void OnnotesChanging(string value);
    partial void OnnotesChanged();
    #endregion
		
		public PMCompanySite()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string siteName
		{
			get
			{
				return this._siteName;
			}
			set
			{
				if ((this._siteName != value))
				{
					this.OnsiteNameChanging(value);
					this.SendPropertyChanging();
					this._siteName = value;
					this.SendPropertyChanged("siteName");
					this.OnsiteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_practice", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int practice
		{
			get
			{
				return this._practice;
			}
			set
			{
				if ((this._practice != value))
				{
					this.OnpracticeChanging(value);
					this.SendPropertyChanging();
					this._practice = value;
					this.SendPropertyChanged("practice");
					this.OnpracticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteId", DbType="NVarChar(50)")]
		public string siteId
		{
			get
			{
				return this._siteId;
			}
			set
			{
				if ((this._siteId != value))
				{
					this.OnsiteIdChanging(value);
					this.SendPropertyChanging();
					this._siteId = value;
					this.SendPropertyChanged("siteId");
					this.OnsiteIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sitePass", DbType="NVarChar(50)")]
		public string sitePass
		{
			get
			{
				return this._sitePass;
			}
			set
			{
				if ((this._sitePass != value))
				{
					this.OnsitePassChanging(value);
					this.SendPropertyChanging();
					this._sitePass = value;
					this.SendPropertyChanged("sitePass");
					this.OnsitePassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siteUrl", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string siteUrl
		{
			get
			{
				return this._siteUrl;
			}
			set
			{
				if ((this._siteUrl != value))
				{
					this.OnsiteUrlChanging(value);
					this.SendPropertyChanging();
					this._siteUrl = value;
					this.SendPropertyChanged("siteUrl");
					this.OnsiteUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastChanged", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lastChanged
		{
			get
			{
				return this._lastChanged;
			}
			set
			{
				if ((this._lastChanged != value))
				{
					this.OnlastChangedChanging(value);
					this.SendPropertyChanging();
					this._lastChanged = value;
					this.SendPropertyChanged("lastChanged");
					this.OnlastChangedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_notes", DbType="NVarChar(MAX)")]
		public string notes
		{
			get
			{
				return this._notes;
			}
			set
			{
				if ((this._notes != value))
				{
					this.OnnotesChanging(value);
					this.SendPropertyChanging();
					this._notes = value;
					this.SendPropertyChanged("notes");
					this.OnnotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
