<?xml version="1.0" encoding="utf-8"?><Database Name="master" Class="L2SAccessDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=3JS0082\justinsqlexpress;Initial Catalog=master;Integrated Security=True" SettingsObjectName="Password_Manager.Properties.Settings" SettingsPropertyName="masterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PMUsers" Member="PMUsers">
    <Type Name="PMUser">
      <Column Name="PMUsername" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PMPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateRegistered" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PMSites" Member="PMSites">
    <Type Name="PMSite">
      <Column Name="siteName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="siteUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="siteId" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sitePass" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lastChanged" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>